dist: bionic

language: python

sudo: required

notifications:
  email: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - python-dev
      - python3-dev
      - libgdal-dev
      - python-gdal
      - python3-gdal
      - gdal-bin
      - build-essential
      - libssl-dev
      - libffi-dev

python:
  - '2.7'
  - '3.6'

virtualenv:
  system_site_packages: true

install:
  - pip install --ignore-installed numpy==1.16.1 cython pathlib
  - pip install .

script:
  - python setup.py test
